name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Postman CLI using Git Bash
        shell: bash
        run: |
          curl -o install-postman.sh https://dl-cli.pstmn.io/install/linux64.sh
          bash install-postman.sh
      
      - name: Login to Postman CLI
        shell: bash
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        shell: bash
        run: postman collection run "31343033-54677bd1-c884-45fa-bc57-eac2666fae54"

